//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artigos
    {
        public int IdArtigo { get; set; }
        public string NomeArtigo { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<int> StockMinimo { get; set; }
        public Nullable<int> IdEntidade { get; set; }
        public Nullable<int> IdTipoDeArtigo { get; set; }
        public Nullable<int> IdMovimento { get; set; }
    
        public virtual Movimentos Movimentos { get; set; }
        public virtual TipoDeArtigo TipoDeArtigo { get; set; }
    }
}
